In [1]:
# -*- codding: utf-8 -*-
import numpy as np
from numpy.linalg import inv
from numpy import dot
from numpy import mat

# 复习numpy矩阵向量运算

In [3]:
A = np.mat([1,1]) # 2*1 矩阵
A

matrix([[1, 1]])

In [5]:
B = mat([[1,2],[2,3]]) # 2*2 矩阵
B

matrix([[1, 2],
        [2, 3]])

In [6]:
A.dot(B)

matrix([[3, 5]])

In [8]:
B.dot(A.T)

matrix([[3],
        [5]])

In [9]:
inv(B) # B的逆矩阵

matrix([[-3.,  2.],
        [ 2., -1.]])

In [10]:
B.dot(inv(B))

matrix([[1., 0.],
        [0., 1.]])

# 最小二乘法

y=2x

In [15]:
X = mat([1,2,3]).reshape(3,1)
Y = 2*X

theta = (X'X)^-1(X'Y)

In [17]:
theta = dot( dot( inv( dot(X.T,X)),X.T),Y)
theta

matrix([[2.]])