# 数组

In [4]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,6,6])

In [13]:
a

array([1, 2, 3, 4, 6, 6])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [14]:
a = a.reshape((2,-1))

In [15]:
a.shape

(2, 3)

In [16]:
a

array([[1, 2, 3],
       [4, 6, 6]])

In [17]:
a = np.zeros((3,3))

In [18]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a = np.full((3,3),2) # 第一个参数是元组
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

# eye

In [22]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# random.random

In [24]:
print(np.random.random((3,4)))

[[0.00473851 0.83093231 0.63897647 0.15184261]
 [0.58789484 0.70669563 0.77196604 0.98007871]
 [0.82859128 0.32747446 0.83266573 0.85328041]]


# indexing

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = a.reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [43]:
np.arange(3)
a[np.arange(3),1] += 10
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [44]:
a[[0,1,2],[0,1,2]] += 10
a

array([[11, 12,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 20, 21, 12]])

In [48]:
result_index = a> 10
result_index

array([[ True,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [49]:
a[result_index]

array([11, 12, 26, 20, 21, 12])

In [50]:
a[a>20]

array([26, 21])

# 元素的数据类型

In [52]:
a.dtype

dtype('int32')

In [53]:
a= np.array([1.1,2,3],dtype=np.int64)

In [54]:
a.dtype

dtype('int64')

In [55]:
a

array([1, 2, 3], dtype=int64)

# 数学运算与常用函数

In [56]:
a = np.array([[1,2],[3,4]])
b = a*2

In [57]:
a
b

array([[2, 4],
       [6, 8]])

In [58]:
a+b

array([[ 3,  6],
       [ 9, 12]])

In [59]:
np.add(b,3)

array([[ 5,  7],
       [ 9, 11]])

In [60]:
b

array([[2, 4],
       [6, 8]])

In [61]:
a*b # 对应位置相乘

array([[ 2,  8],
       [18, 32]])

In [62]:
np.multiply(a,b)

array([[ 2,  8],
       [18, 32]])

In [63]:
b/a

array([[2., 2.],
       [2., 2.]])

In [64]:
ba = b/a

In [65]:
ba.dtype

dtype('float64')

In [70]:
ba = np.array(ba,dtype=np.int64)
ba

array([[2, 2],
       [2, 2]], dtype=int64)

In [71]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [73]:
print(a)
print(b)
a.dot(b)  # 矩阵乘法

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


array([[14, 20],
       [30, 44]])

In [74]:
np.dot(a,b)

array([[14, 20],
       [30, 44]])

## 常用函数

sum

In [75]:
a

array([[1, 2],
       [3, 4]])

In [76]:
np.sum(a)

10

In [77]:
np.sum(a,axis=0) # 数组中的每一列求和

array([4, 6])

In [78]:
np.sum(a,axis=1) # 数组中的每一行求和

array([3, 7])

mean 平均值

In [79]:
np.mean(a)

2.5

In [80]:
np.mean(a,axis=0)

array([2., 3.])

uniform 产生局域随机数

In [81]:
np.random.uniform(3,4)

3.3637842314604254

tile 重复

In [82]:
a

array([[1, 2],
       [3, 4]])

In [83]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [84]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [85]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

argsort

In [87]:
a = np.array([[6,2,4,5],[9,4,0,6]])
a

array([[6, 2, 4, 5],
       [9, 4, 0, 6]])

In [88]:
a.argsort() # 每一行 进行排序，升序，返回下标

array([[1, 2, 3, 0],
       [2, 1, 3, 0]], dtype=int64)

In [89]:
a.argsort(axis=0) # 对每一列排序

array([[0, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int64)

矩阵转置

In [90]:
a

array([[6, 2, 4, 5],
       [9, 4, 0, 6]])

In [91]:
a.T

array([[6, 9],
       [2, 4],
       [4, 0],
       [5, 6]])

In [93]:
np.transpose(a)

array([[6, 9],
       [2, 4],
       [4, 0],
       [5, 6]])

# 广播

In [105]:
a = np.array([[1,2,3],[2,3,4],[12,31,22],[2,2,2]])
a

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [12, 31, 22],
       [ 2,  2,  2]])

In [100]:
b = np.array([1,2,3])

In [106]:
for i in range(4):
    a[i,:] += b
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [107]:
a + np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [108]:
a + b # numpy的广播 自动转化数组维度

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])